### ISSUE TITLE
Enable creating child class constructor

### ISSUE THREAD

**Issue by McGeifer** [samangh/wamplv#4]
Hello!

First of all thanks for this nice library and the work you put into it 👍

I'm currently working on a project that involves quite a lot of WAMP calls. Due to the nature of the WAMP server I have to speak to I need to add a "disclose_me:true" option to basically all calls I make. To make life a bit easier I decided to override your Call & Call (async) methods, add the disclose_me option to the call if needed and then simply call the parent method. After creting the child class I unfortunately ran into a problem.

You constructor "New Client.vi" is using a bundle by name to save the "Transport Type" enum & "Enable TLS?" flag. When creating the constructor for my child class I can't set these properties cause they have no accessor VIs. Without an option to set these properties the library obviously is not working.

I would call myself a beginner in OOP so I'm not sure if my suggestion is the best solution but adding public or better protected accessors for these porperties would solve this problem. So I could basically "copy" your constructor and use my ovverride methods.

![grafik](https://github.com/user-attachments/assets/c0fbb5a3-7128-428a-98d5-fc7ba6b3929e)
![grafik](https://github.com/user-attachments/assets/9c1781d2-c653-49ec-a01b-8e5a79a8cc31)

If you want I could create an pull request with my changes. It is developed with LV 2020 right?

**Comment by samangh** [comment]
I'm glad to hear that this library has been of use to you :-).

I would suggest against copying the constructor. This would make the whole thing rather fragile, because if the `wamplv` constructor ever changes then you will have to remember to modify your copy too. For a similar reason I'm hesitant to make the internals of the library too visible to any child classes.

In the latest commit I have moved all the constructor stuff to `Private/SubVIs/Setup Connection.vi`. You can use it in your child class like so to setup everything:

![image](https://github.com/user-attachments/assets/625db05b-db68-4934-af6a-87946b88c974)

Does this work for you?

**Comment by McGeifer** [comment]
Thanks for you quick response. Copying the constructor did seem not right to me either but I don't know how to do it otherwise. To be honest I'm not sure how I should use this VI? I still need to basicaly copy the entire constructor only the bundle/ propertie node is no longer needed.

**Comment by samangh** [comment]
@McGeifer No, this way you don't have to copy the constructor. All the constructor logic has moved to a separate VI. I've renamed this VI to `Setup Client.vi` to make this more clear.

To fully construct your child class, simply pass a copy of your child class to `Setup Client.vi`. If you like, in your child class you can create a `New Client.vi` that does this as I showed in my previous message.

**Comment by samangh** [comment]
@McGeifer I'm very curious to learn about where wamlv is being used :-). If you don't mind and are allowed to, can I ask what your project is?

**Comment by McGeifer** [comment]
> @McGeifer No, this way you don't have to copy the constructor. All the constructor logic has moved to a separate VI. I've renamed this VI to `Setup Client.vi` to make this more clear.
> 
> To fully construct your child class, simply pass a copy of your child class to `Setup Client.vi`. If you like, in your child class you can create a `New Client.vi` that does this as I showed in my previous message.

Worked like a charm 👍

> @McGeifer I'm very curious to learn about where wamlv is being used :-). If you don't mind and are allowed to, can I ask what your project is?

We are currently developing a new software for the devices we produce. This software is using a webinterface as an GUI and almost all the communication with the devices and the frontend/backend is done with WAMP procedures and topics. I on the other hand develop a LabVIEW programm for internal use which is calling a few of the backend functions. The backend is writen in .net 8 so there is no other way then using the WAMP connection. To be honest this is quite a lot easier then I imagined in comparison to interact with the backend library and .Net. So thanks again for you work!

Are there plans to implement Progressive Call Results?

**Comment by samangh** [comment]
Great. Thanks for the explanation, glad to hear that the library has proved useful.

There were no plans to add progressive calls until now, but they should be straighforward to implement. I'll add it to my to do list :-).
